HelpDesk.WeUI/Models/ClientRequest.cs
using System.ComponentModel.DataAnnotations;
using HelpDesk.WebUI.Models;
using HelpDesk.WebUI.Enum;

namespace HelpDesk.WebUI.Models
{
    public partial class ClientRequest : GeneralModel
    {
        [Key]
        public int RequestId { get; set; }

        [Display(Name = "Customer Name")]
        public string ClientName { get; set; }

        [Display(Name = "Request Description")]
        public string RequestDescription { get; set; }

        [Display(Name = "Request Type")]
        public string? RequestType { get; set; }

        [Display(Name = "Request Status")]
        public RequestStatus? RStatus { get; set; } = RequestStatus.Waiting;

        [Display(Name = "Request Date")]
        public DateTime RequestDate { get; set; }

        [Display(Name = "Response Date")]
        public DateTime? ResponseDate { get; set; }

        [Display(Name = "Employee Response")]
        public string? Response { get; set; }

        [Display(Name = "Assigned Employee")]
        public string AppUserId { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}

HelpDesk.WeUI/Controllers/ClientRequestsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelpDesk.WebUI.Data;
using HelpDesk.WebUI.Models;
using System.Net.NetworkInformation;
using Microsoft.AspNetCore.Identity;

namespace HelpDesk.WebUI.Controllers
{
    public class ClientRequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public ClientRequestsController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ClientRequests
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.clientRequests.Include(c => c.AppUser);

            /*var clientRequests = await applicationDbContext.ToListAsync();

            // Map the ID to the Name for each client request
            foreach (var clientRequest in clientRequests)
            {
                clientRequest.AppUserId = clientRequest.AppUser.UserName;
            }

            return View(clientRequests);*/
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ClientRequests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.clientRequests == null)
            {
                return NotFound();
            }

            var clientRequest = await _context.clientRequests
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (clientRequest == null)
            {
                return NotFound();
            }

            return View(clientRequest);
        }

        // GET: ClientRequests/Create
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Name");
            return View();
        }

        // POST: ClientRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RequestId,ClientName,RequestDescription,RequestType,RStatus,RequestDate,ResponseDate,Response,AppUserId,CreatedIn,CreatedBy,ModifiedIn,ModifiedBy")] ClientRequest clientRequest)
        {
            if (ModelState.IsValid)
            {
                clientRequest.RStatus = Enum.RequestStatus.Waiting;
                clientRequest.RequestDate = DateTime.Now;
                var request = new ClientRequest
                {
                    RStatus = clientRequest.RStatus,
                    RequestDate = clientRequest.RequestDate
                };
                _context.Add(clientRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Name", clientRequest.AppUserId);
            return View(clientRequest);
        }

        // GET: ClientRequests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.clientRequests == null)
            {
                return NotFound();
            }

            var clientRequest = await _context.clientRequests.FindAsync(id);
            if (clientRequest == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Name", clientRequest.AppUserId);
            return View(clientRequest);
        }

        // POST: ClientRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RequestId,ClientName,RequestDescription,RequestType,RStatus,RequestDate,ResponseDate,Response,AppUserId,CreatedIn,ModifiedIn")] ClientRequest clientRequest)
        {
            if (id != clientRequest.RequestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    clientRequest.RStatus = Enum.RequestStatus.Waiting;
                    //clientRequest.RequestDate = DateTime.Now;
                    var request = new ClientRequest
                    {
                        RStatus = clientRequest.RStatus,
                        //RequestDate = clientRequest.RequestDate
                    };
                    _context.Update(clientRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientRequestExists(clientRequest.RequestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Name", clientRequest.AppUserId);
            return View(clientRequest);
        }

        // GET: ClientRequests/Assigned/5
        // [Route("clientrequests/assigned/{id}")]
        public async Task<IActionResult> Assigned(int? id)
        {
            if (id == null || _context.clientRequests == null)
            {
                return NotFound();
            }

            var clientRequest = await _context.clientRequests.FindAsync(id);
            if (clientRequest == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Name", clientRequest.AppUserId);
            return View(clientRequest);
        }

        // POST: ClientRequests/Assigned/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Assigned(int id, [Bind("RequestId,ClientName,RequestDescription,RequestType,RStatus,RequestDate,ResponseDate,Response,AppUserId,CreatedIn,ModifiedIn")] ClientRequest clientRequest)
        {
            // clientRequest = await _context.clientRequests.FindAsync(id); 

            if (id != clientRequest.RequestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    clientRequest.RStatus = Enum.RequestStatus.Waiting;
                    //clientRequest.RequestDate = DateTime.Now;
                    var request = new ClientRequest
                    {
                        RStatus = clientRequest.RStatus,
                        //RequestDate = clientRequest.RequestDate
                    };
                    _context.Update(clientRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientRequestExists(clientRequest.RequestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(My_Request));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Name", clientRequest.AppUserId);
            return View(clientRequest);
        }

        // GET: ClientRequests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.clientRequests == null)
            {
                return NotFound();
            }

            var clientRequest = await _context.clientRequests
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (clientRequest == null)
            {
                return NotFound();
            }

            return View(clientRequest);
        }

        // POST: ClientRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.clientRequests == null)
            {
                return Problem("Entity set 'ApplicationDbContext.clientRequests'  is null.");
            }
            var clientRequest = await _context.clientRequests.FindAsync(id);
            if (clientRequest != null)
            {
                _context.clientRequests.Remove(clientRequest);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: All Client Requests For The Employee
        public async Task<IActionResult> My_Request()
        {
            // استعلام لاسترداد الطلبات المرتبطة بالموظف الحالي
            var employeeRequests = await _context.clientRequests
            .Include(c => c.AppUser)
                .Where(c => c.AppUser.Id == _userManager.GetUserId(User))
                .ToListAsync();

            return View(employeeRequests);
        }

        // GET: ClientRequests/ReviewDetails/5
        public async Task<IActionResult> ReviewDetails(int? id)
        {
            if (id == null || _context.clientRequests == null)
            {
                return NotFound();
            }

HelpDesk.WeUI/Views/ClientRequests/Assigned.cshtml
@model HelpDesk.WebUI.Models.ClientRequest

@{
    ViewData["Title"] = "Assigned";
}

<h1>Assign to anothor Employee</h1>

<h4>Client Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Assigned">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RequestId" />
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="AppUserId" class="control-label"></label>
                <select asp-for="AppUserId" class="form-control" asp-items="ViewBag.AppUserId"></select>
                <span asp-validation-for="AppUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="My_Request" class="btn btn-outline-info">Back to List</a>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold; visibility:hidden">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold; visibility:hidden">
                <label asp-for="RequestDescription" class="control-label"></label>
                <input asp-for="RequestDescription" class="form-control" />
                <span asp-validation-for="RequestDescription" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold; visibility:hidden">
                <label asp-for="RequestType" class="control-label"></label>
                <input asp-for="RequestType" class="form-control" />
                <span asp-validation-for="RequestType" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold; visibility:hidden">
                <label asp-for="RStatus" class="control-label"></label>
                <input asp-for="RStatus" class="form-control" />
                <span asp-validation-for="RStatus" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold; visibility:hidden">
                <label asp-for="RequestDate" class="control-label"></label>
                <input asp-for="RequestDate" class="form-control" />
                <span asp-validation-for="RequestDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold; visibility:hidden">
                <label asp-for="ResponseDate" class="control-label"></label>
                <input asp-for="ResponseDate" class="form-control" />
                <span asp-validation-for="ResponseDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold; visibility:hidden">
                <label asp-for="Response" class="control-label"></label>
                <input asp-for="Response" class="form-control" />
                <span asp-validation-for="Response" class="text-danger"></span>
            </div>
            
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelpDesk.WeUI/Views/ClientRequests/Create.cshtml
@model HelpDesk.WebUI.Models.ClientRequest

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ClientRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RequestDescription" class="control-label"></label>
                <input asp-for="RequestDescription" class="form-control" />
                <span asp-validation-for="RequestDescription" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RequestType" class="control-label"></label>
                <input asp-for="RequestType" class="form-control" />
                <span asp-validation-for="RequestType" class="text-danger"></span>
            </div>
            @*<div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RStatus" class="control-label"></label>
                <input asp-for="RStatus" class="form-control" />
                <span asp-validation-for="RStatus" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RequestDate" class="control-label"></label>
                <input asp-for="RequestDate" class="form-control" />
                <span asp-validation-for="RequestDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="ResponseDate" class="control-label"></label>
                <input asp-for="ResponseDate" class="form-control" />
                <span asp-validation-for="ResponseDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="Response" class="control-label"></label>
                <input asp-for="Response" class="form-control" />
                <span asp-validation-for="Response" class="text-danger"></span>
            </div>*@
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="AppUserId" class="control-label"></label>
                <select asp-for="AppUserId" class ="form-control" asp-items="ViewBag.AppUserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelpDesk.WeUI/Views/ClientRequests/Delete.cshtml
@model HelpDesk.WebUI.Models.ClientRequest

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class="col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RequestDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestDescription)
        </dd>
        <dt class="col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RequestType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestType)
        </dd>
        <dt class="col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RStatus)
        </dd>
        <dt class = "col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RequestDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestDate)
        </dd>
        <dt class="col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.ResponseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResponseDate)
        </dd>
        <dt class="col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.Response)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Response)
        </dd>
        <dt class="col-sm-2" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.AppUserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppUser.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RequestId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
    </form>
</div>

HelpDesk.WeUI/Views/ClientRequests/Details.cshtml
@model HelpDesk.WebUI.Models.ClientRequest

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ClientRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RequestDescription)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.RequestDescription)
        </dd>
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RequestType)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.RequestType)
        </dd>
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RStatus)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.RStatus)
        </dd>
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.RequestDate)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.RequestDate)
        </dd>
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.ResponseDate)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.ResponseDate)
        </dd>
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.Response)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Response)
        </dd>
        <dt class="col-sm-4" style="font-size:20px; font-weight:bold">
            @Html.DisplayNameFor(model => model.AppUserId)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.AppUser.UserName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.RequestId" class="btn btn-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

HelpDesk.WeUI/Views/ClientRequests/Edit.cshtml
@model HelpDesk.WebUI.Models.ClientRequest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Client Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RequestId" />
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RequestDescription" class="control-label"></label>
                <input asp-for="RequestDescription" class="form-control" />
                <span asp-validation-for="RequestDescription" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RequestType" class="control-label"></label>
                <input asp-for="RequestType" class="form-control" />
                <span asp-validation-for="RequestType" class="text-danger"></span>
            </div>
            @*<div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RStatus" class="control-label"></label>
                <input asp-for="RStatus" class="form-control" />
                <span asp-validation-for="RStatus" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="RequestDate" class="control-label"></label>
                <input asp-for="RequestDate" class="form-control" />
                <span asp-validation-for="RequestDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="ResponseDate" class="control-label"></label>
                <input asp-for="ResponseDate" class="form-control" />
                <span asp-validation-for="ResponseDate" class="text-danger"></span>
            </div>*@
            @*<div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="Response" class="control-label"></label>
                <input asp-for="Response" class="form-control" />
                <span asp-validation-for="Response" class="text-danger"></span>
            </div>*@
            <div class="form-group" style="font-size:20px; font-weight:bold">
                <label asp-for="AppUserId" class="control-label"></label>
                <select asp-for="AppUserId" class="form-control" asp-items="ViewBag.AppUserId"></select>
                <span asp-validation-for="AppUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelpDesk.WeUI/Views/ClientRequests/ReviewDetails.cshtml
@model HelpDesk.WebUI.Models.ClientRequest

@{
    ViewData["Title"] = "Leave Request Details";
    string className;
    string headingText;
    if (Model.RStatus == HelpDesk.WebUI.Enum.RequestStatus.Waiting)
    {
        headingText = "Pending Approval";
        className = "warning";
    }
    else if (Model.RStatus == HelpDesk.WebUI.Enum.RequestStatus.Accepted)
    {
        headingText = "Approved";
        className = "success";
    }
    else
    {
        headingText = "Rejected";
        className = "danger";
    }
}

<h1>Leave Request Details</h1>

<div class="alert alert-@className" role="alert">
    <h4 class="alert-heading">@headingText</h4>
    <hr>
    <p>
        <strong>Customer Name:</strong>  @Model.ClientName
    </p>
    <hr />
    <p>
        <strong>Requested Date:</strong> @Html.DisplayFor(model => model.RequestDate)
    </p>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Response)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Response)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AppUserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AppUserId)
        </dd>
    </dl>
</div>
<div>
    <div class="row">
        @if (Model.RStatus == HelpDesk.WebUI.Enum.RequestStatus.Waiting)
        {

            <div class="col">
                <form asp-controller="ClientRequests" asp-action="ReviewEdit" class="form-inline">
                    <input name="Id" value="@Model.RequestId" type="hidden" />
                    <input name="rStatusForm" type="hidden" value="true" />
                    <button type="submit" class="btn btn-success btn-lg">Accept</button>
                </form>
            </div>
            <div class="col">
                <form asp-controller="ClientRequests" asp-action="ReviewEdit" class="form-inline">
                    <input name="Id" value="@Model.RequestId" type="hidden" />
                    <input name="rStatusForm" type="hidden" value="false" />
                    <button type="submit" class="btn btn-danger btn-lg">Reject</button>
                </form>
            </div>
        }
        <div class="col">
            <a class="btn btn-dark btn-lg" asp-action="My_Request">Back to List</a>
        </div>
    </div>
    
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}